In [15]:
import warnings
warnings.filterwarnings(action='ignore')
import numpy as np

In [28]:
arr = np.arange(32)
print(arr)
print(len(arr))
print(type(arr))
print(arr.shape)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31]
32
<class 'numpy.ndarray'>
(32,)


In [29]:
# reshape() 메소드는 numpy 배열의 차원을 변경한다. => 전체 데이터 개수는 같아야 한다.
v = arr.reshape(4,2,4) # depth 4, 2 rows, 2 cols.
# 항상 행 기준!!
print(v) 
print(v.shape)

[[[ 0  1  2  3]
  [ 4  5  6  7]]

 [[ 8  9 10 11]
  [12 13 14 15]]

 [[16 17 18 19]
  [20 21 22 23]]

 [[24 25 26 27]
  [28 29 30 31]]]
(4, 2, 4)


numpy의 sum() 메소드 :  전체 합계 혹은 축 합계를 구한다.

axis=None은 기본값으로 모든 요소의 값을 합산하여 1개의 스칼라값을 반환합니다.  
axis=0은 x축을 기준으로 여러 row를 한 개로 합치는 과정입니다.  
axis=1은 y축을 기준으로 row 별로 존재하는 column들의 값을 합쳐 1개로 축소하는 과정입니다.  
axis=2는 z축을 기준으로 column의 depth가 가진 값을 축소하는 과정입니다.

행이 늘어나는 방향이 위에서 아래 = 행 방향

 

열이 늘어나는 방향이 좌에서 우 = 열 방향

내적을 계산 : 첫 번째 행렬의 각 행과 두 번째 행렬의 각 열을 순서대로 곱하고 더해야 합니다.

In [30]:
# sum() 메소드의 axis 속성의 기본값은 None이고 axis는 대상 차원보다 작은 값을 설정한다.
# 위의 예제에서는 데이터의 차원이 3이기 때문에 axis 속성은 2까지 지정할 수 있다.
print(v.ndim) # ndim: numpy 배열의 차원(Dimension)을 얻어온다.


3


In [23]:
# axis=None
# 기본값. 면, 행, 열을 구분않고 전체 합계를 계산한다.
# 데이터에 포함된 모든 요소를 합산.
print(v.shape)
print(v.sum()) # print(v.sum(axis=None))와 같은 표현이다.
print(v.sum(axis=None))

(4, 2, 4)
496
496


In [24]:
# axis=0 
# !x축 행!을 합친다 ... 기준으로 계산한 합계를 리턴한다.
# => 컬럼과 depth의 위치별 합이 계산됩니다.

# shape이 (4, 2, 4)인 데이터를 x축을 기준으로 계산
res = v.sum(axis=0)
print(res.shape) # 면이 제거되고 (2, 4)이 리턴된다.
print(res.ndim)
print(res)
# axis=0은 가장 외곽의 괄호를 제거하고 각 행의 데이터는 위치별로 합계를 계산한다.


(2, 4)
2
[[48 52 56 60]
 [64 68 72 76]]


In [ ]:
# axis=1
# y축 즉 컬럼을 합친다... sum
# => row 별로 컬럼들의 depth 위치별 합이 계산됩니다.

# shape이 (4, 2, 4)인 데이터를 y축을 기준을 계산한 결과 shape은 열이 제거되고 (4, 4)이 리턴된다.
res = v.sum(axis=1)
print(res.shape)
print(res.ndim)
print(res)

In [31]:
# axis=2
# axis=2는 z축을 기준으로 계산한 합계를 리턴한다.
# shape이 (4, 2, 4)인 데이터를 y축을 기준을 계산한 결과 shape은 열이 제거되고 (4, 2)이 리턴된다.
res = v.sum(axis=2)
print(res.shape)
print(res.ndim)
print(res)

(4, 2)
2
[[  6  22]
 [ 38  54]
 [ 70  86]
 [102 118]]
