In [55]:
import warnings
warnings.filterwarnings('ignore')
import numpy as np

def pprint(arr):
    print('type: {}'.format(type(arr)))
    print('shape: {}, dimension: {}, dtype: {}'.format(arr.shape, arr.ndim, arr.dtype))
    print('numpy 배열의 데이터\n', arr, sep='')

numpy의 sum() 메소드 :  전체 합계 혹은 축 합계를 구한다.

axis=None은 기본값으로 모든 요소의 값을 합산하여 1개의 스칼라값을 반환합니다.  
axis=0은 x축을 기준으로 여러 row를 한 개로 합치는 과정입니다.  
axis=1은 y축을 기준으로 row 별로 존재하는 column들의 값을 합쳐 1개로 축소하는 과정입니다.  
axis=2는 z축을 기준으로 column의 depth가 가진 값을 축소하는 과정입니다.

행이 늘어나는 방향이 위에서 아래 = 행 방향

 

열이 늘어나는 방향이 좌에서 우 = 열 방향

내적을 계산 : 첫 번째 행렬의 각 행과 두 번째 행렬의 각 열을 순서대로 곱하고 더해야 합니다.

In [57]:
# numpy는 배열 객체를 바이너리(2진) 파일 또는 텍스트 파일에 저장하고 로딩하는 기능을 제공한다.
# 메소드 이름     기능                                                 파일 포맷
# np.save()       numpy 배열 객체 1개를 파일로 저장한다.               바이너리
# np.savez()      numpy 배열 객체 여러 개를 파일로 저장한다.           바이너리
# np.load()       numpy 배열 객체를 읽어온다.                          바이너리
# ============================================================================================
# np.savetxt()    numpy 배열 객체 텍스트 파일로 저장한다.              텍스트
# np.loadtxt()    numpy 배열 객체를 읽어온다.                          텍스트

In [13]:
a = np.random.randint(0, 10, (2, 3))
print(a)
b = np.random.randint(0, 10, (2, 3))
print(b)

[[2 9 3]
 [0 0 0]]
[[7 2 1]
 [5 4 1]]


In [11]:
# numpy 배열 객체를 바이너리 파일로 저장
# np.save(): 배열 1개를 저장. 확장자 => npy
# np.savez(): 배열 여러 개를 저장. 확장자 => npz

# a 배열을 바이너리 파일로 저장한다.
# np.save('경로명', 배열명)
np.save('./output/my_array1', a)
# a, b 배열을 바이너리 파일로 저장한다.
# np.savez('경로명', 배열명1, 배열명2, ...)
np.savez('./output/my_array2', a, b)

In [12]:
# np.load() 메소드로 npy, npz 파일로 부터 배열 데이터를 읽어올 수 있다.
# npy 파일 읽기
print(np.load('./output/my_array1.npy'))

# npz 파일 읽기
print(np.load('./output/my_array2.npz'))
npzFiles = np.load('./output/my_array2.npz')
print(npzFiles['arr_0'])
print(npzFiles['arr_1'])

[[3 6 2]
 [4 6 1]]
[[3 6 2]
 [4 6 1]]
[[8 6 3]
 [1 4 8]]


In [15]:
c = np.random.random((3, 4))
pprint(c)

type: <class 'numpy.ndarray'>
shape: (3, 4), dimension: 2, dtype: float64
numpy 배열의 데이터
[[0.35422889 0.94842168 0.68732152 0.03960771]
 [0.18550614 0.86689136 0.96115908 0.75469707]
 [0.44906151 0.33030967 0.65748356 0.03090981]]


In [16]:
# numpy 배열 객체를 텍스트 파일로 저장
# 텍스트 파일 : csv 또는 tsv 파일을 의미한다.
# np.savetxt() 메소드로 배열 객체를 텍스트 파일 형태로 저장시킬 수 있다.
# np.savetxt('경로명', 배열명, delimiter='구분자')
np.savetxt('./output/saved.csv', c, delimiter=',') # csv 파일은 데이터를 ','로 구분한다.
np.savetxt('./output/saved2.tsv', c, delimiter='\t') # tsv 파일은 데이터를 tab(\t)으로 구분한다.

In [17]:
# np.loadtxt() 메소드로 배열 객체를 텍스트 파일 형태로 저장시킬 수 있다.
# np.loadtxt('경로명', dtype, delimiter='구분자')
saved = np.loadtxt('./output/saved.csv', dtype=np.float, delimiter=',')
pprint(saved)
print(np.loadtxt('./output/saved2.tsv', dtype=float, delimiter='\t'))

type: <class 'numpy.ndarray'>
shape: (3, 4), dimension: 2, dtype: float64
numpy 배열의 데이터
[[0.35422889 0.94842168 0.68732152 0.03960771]
 [0.18550614 0.86689136 0.96115908 0.75469707]
 [0.44906151 0.33030967 0.65748356 0.03090981]]
[[0.35422889 0.94842168 0.68732152 0.03960771]
 [0.18550614 0.86689136 0.96115908 0.75469707]
 [0.44906151 0.33030967 0.65748356 0.03090981]]


배열(행렬) 연산 - 산술 연산

In [19]:
a = np.arange(1, 10).reshape(3, 3)
pprint(a)
b = np.arange(9, 0, -1).reshape(3, 3)
pprint(b)

type: <class 'numpy.ndarray'>
shape: (3, 3), dimension: 2, dtype: int32
numpy 배열의 데이터
[[1 2 3]
 [4 5 6]
 [7 8 9]]
type: <class 'numpy.ndarray'>
shape: (3, 3), dimension: 2, dtype: int32
numpy 배열의 데이터
[[9 8 7]
 [6 5 4]
 [3 2 1]]


In [23]:
# 덧셈: +, np.add()
print(a + b)
print(np.add(a, b))
print('='*80)
# 뺄셈: -, np.subtract()
print(a - b)
print(np.subtract(a, b))
print('='*80)

# 곱셈: *, np.multiply()
print(a * b)
print(np.multiply(a, b))
print('='*80)

# 나눗셈
print(a / b)
print(a // b) # 정수 나누기
print(a % b) # 나머지
print(np.divide(a, b))

[[10 10 10]
 [10 10 10]
 [10 10 10]]
[[10 10 10]
 [10 10 10]
 [10 10 10]]
[[-8 -6 -4]
 [-2  0  2]
 [ 4  6  8]]
[[-8 -6 -4]
 [-2  0  2]
 [ 4  6  8]]
[[ 9 16 21]
 [24 25 24]
 [21 16  9]]
[[ 9 16 21]
 [24 25 24]
 [21 16  9]]
[[0.11111111 0.25       0.42857143]
 [0.66666667 1.         1.5       ]
 [2.33333333 4.         9.        ]]
[[0 0 0]
 [0 1 1]
 [2 4 9]]
[[1 2 3]
 [4 0 2]
 [1 0 0]]
[[0.11111111 0.25       0.42857143]
 [0.66666667 1.         1.5       ]
 [2.33333333 4.         9.        ]]


In [25]:
print(np.exp(a)) # 지수
print('='*80)

print(np.sqrt(a))
print('='*80)

# 삼각함수
print(np.sin(a))
print(np.cos(a))
print(np.tan(a))
print('='*80)

print(np.log(a)) # 로그

[[2.71828183e+00 7.38905610e+00 2.00855369e+01]
 [5.45981500e+01 1.48413159e+02 4.03428793e+02]
 [1.09663316e+03 2.98095799e+03 8.10308393e+03]]
[[1.         1.41421356 1.73205081]
 [2.         2.23606798 2.44948974]
 [2.64575131 2.82842712 3.        ]]
[[ 0.84147098  0.90929743  0.14112001]
 [-0.7568025  -0.95892427 -0.2794155 ]
 [ 0.6569866   0.98935825  0.41211849]]
[[ 0.54030231 -0.41614684 -0.9899925 ]
 [-0.65364362  0.28366219  0.96017029]
 [ 0.75390225 -0.14550003 -0.91113026]]
[[ 1.55740772 -2.18503986 -0.14254654]
 [ 1.15782128 -3.38051501 -0.29100619]
 [ 0.87144798 -6.79971146 -0.45231566]]
[[0.         0.69314718 1.09861229]
 [1.38629436 1.60943791 1.79175947]
 [1.94591015 2.07944154 2.19722458]]


In [59]:
# 행렬의 내적
print(np.dot(a,b))

[[ 30  24  18]
 [ 84  69  54]
 [138 114  90]]


In [29]:
# 배열 요소별 비교: >, >=, <, <=, ==, !=
print(a == b)

[[False False False]
 [False  True False]
 [False False False]]


In [30]:
# np.array_equal() 메소드를 사용하면 배열 전체를 비교할 수 있다.
print(np.array_equal(a, b))

False


집계 함수  
numpy의 모든 집계 함수는 axis를 기준으로 계산하며 집계 함수에 axis를 지정하지 않으면 axis=None이 기본값으로 사용된다.


In [36]:
a = np.arange(1, 10).reshape(3, 3)
pprint(a)

type: <class 'numpy.ndarray'>
shape: (3, 3), dimension: 2, dtype: int32
numpy 배열의 데이터
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [37]:
# axis=None
# axis=None은 전체 배열 합계를 계산한다. 기본값으로 사용된다.
print(a.sum())
print(a.sum(axis=None))
print(np.sum(a))
print(np.sum(a, axis=None))

45
45
45
45


In [39]:
# axis=0
# axis=0은 x축을 기준으로 여러 row를 한 개로 합치는 과정입니다.
print(a.sum(axis=0))
print(np.sum(a, axis=0))
print('='*80)


# axis=1
# axis=1은 y축을 기준으로 row 별로 존재하는 column들의 값을 합쳐 1개로 축소하는 과정
print(a.sum(axis=1))
print(np.sum(a, axis=1))

[12 15 18]
[12 15 18]
[ 6 15 24]
[ 6 15 24]


최대값: 배열.max(), np.max(배열), 최소값: 배열.min(), np.min(배열)


In [41]:
print(a.max()) 
print(np.max(a)) 
print(a.min()) 
print(np.min(a)) 

9
9
1
1


In [43]:
print(a.max(axis=0))
print(np.max(a, axis=0))
print(a.min(axis=0))
print(np.min(a, axis=0))

[7 8 9]
[7 8 9]
[1 2 3]
[1 2 3]


In [45]:
print(a.max(axis=1))
print(np.max(a, axis=1))
print(a.min(axis=1))
print(np.min(a, axis=1))

[3 6 9]
[3 6 9]
[1 4 7]
[1 4 7]


In [47]:
# 누적 합계: 배열.cumsum(), np.cumsum(배열)
print(a.cumsum())
print(np.cumsum(a))

print(a.cumsum(axis=0))
print(np.cumsum(a, axis=0))

print(a.cumsum(axis=1))
print(np.cumsum(a, axis=1))


[ 1  3  6 10 15 21 28 36 45]
[ 1  3  6 10 15 21 28 36 45]
[[ 1  2  3]
 [ 5  7  9]
 [12 15 18]]
[[ 1  2  3]
 [ 5  7  9]
 [12 15 18]]
[[ 1  3  6]
 [ 4  9 15]
 [ 7 15 24]]
[[ 1  3  6]
 [ 4  9 15]
 [ 7 15 24]]


In [49]:
# 평균: 배열.mean(), np.mean(배열)

print(a.mean())
print(np.mean(a))

print(a.mean(axis=0))
print(np.mean(a, axis=0))

print(a.mean(axis=1))
print(np.mean(a, axis=1))

5.0
5.0
[4. 5. 6.]
[4. 5. 6.]
[2. 5. 8.]
[2. 5. 8.]


In [50]:
# 중위수: np.median(배열)

print(np.median(a))
print(np.median(a, axis=0))
print(np.median(a, axis=1))


5.0
[4. 5. 6.]
[2. 5. 8.]


In [52]:
# 상관계수: np.corrcoef(배열)

print(np.corrcoef(a,)) # axis를 사용하지 않는다.


[[ 1.  1.  1. -1. -1. -1.]
 [ 1.  1.  1. -1. -1. -1.]
 [ 1.  1.  1. -1. -1. -1.]
 [-1. -1. -1.  1.  1.  1.]
 [-1. -1. -1.  1.  1.  1.]
 [-1. -1. -1.  1.  1.  1.]]


In [54]:
# 표준편차: 배열.std(), np.std(배열)

print(a.std())
print(np.std(a))

print(a.std(axis=0))
print(np.std(a, axis=0))

print(a.std(axis=1))
print(np.std(a, axis=1))

2.581988897471611
2.581988897471611
[2.44948974 2.44948974 2.44948974]
[2.44948974 2.44948974 2.44948974]
[0.81649658 0.81649658 0.81649658]
[0.81649658 0.81649658 0.81649658]
