In [1]:
import warnings
warnings.filterwarnings('ignore')
%config Computer.use_jedi = False
import numpy as np

def pprint(arr):
    print('type: {}'.format(type(arr)))
    print('shape: {}, dimension: {}, dtype: {}'.format(arr.shape, arr.ndim, arr.dtype))
    print('numpy 배열의 데이터\n', arr, sep='') 

인덱싱  

[행][열] or [행, 열]과 같이 인덱스를 지정할 수 있다.

!! 0행 0열부터다!!

In [5]:
a = np.arange(24) # 1차원
pprint(a)

b = np.arange(24).reshape(4,6)
pprint(b)

c = np.arange(24).reshape(2,4,3)
pprint(c)

type: <class 'numpy.ndarray'>
shape: (24,), dimension: 1, dtype: int32
numpy 배열의 데이터
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
type: <class 'numpy.ndarray'>
shape: (4, 6), dimension: 2, dtype: int32
numpy 배열의 데이터
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
type: <class 'numpy.ndarray'>
shape: (2, 4, 3), dimension: 3, dtype: int32
numpy 배열의 데이터
[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]
  [18 19 20]
  [21 22 23]]]


In [10]:
# 1차원 배열 요소 참조 및 변경
a[5]=999
pprint(a)

# 2차원
b[2,3]=2323 
pprint(b)

# 3차원
c[0][2][2] =22
c[1,2,0]=120 
pprint(c)

type: <class 'numpy.ndarray'>
shape: (24,), dimension: 1, dtype: int32
numpy 배열의 데이터
[  0   1   2   3   4 999   6   7   8   9  10  11  12  13  14  15  16  17
  18  19  20  21  22  23]
type: <class 'numpy.ndarray'>
shape: (4, 6), dimension: 2, dtype: int32
numpy 배열의 데이터
[[   0    1    2    3    4    5]
 [   6    7    8    9   10   11]
 [  12   13   14 2323   16   17]
 [  18   19   20   21   22   23]]
type: <class 'numpy.ndarray'>
shape: (2, 4, 3), dimension: 3, dtype: int32
numpy 배열의 데이터
[[[  0   1   2]
  [  3   4   5]
  [  6   7  22]
  [  9  10  11]]

 [[ 12  13  14]
  [ 15  16  17]
  [120  19  20]
  [ 21  22  23]]]


슬라이싱 ! 약점.

[a,b] : a이상 b미만 슬라이스

[0, -1] : 0이상 마지막미만

In [31]:
#1차원
print(a)
print(a[2:6]) # index 2이상 6미만 슬라이스
    
#2차원
print(b) #3행 5열
print("="*80)

print(b[:,2:4]) # 전체행, 2이상3미만열
print("="*80)

print(b[1:3,1:5]) # 1이상3미만행, 1이상5미만열
print("="*80)

# -1 : 마지막 인덱스
print(b[1:-1,1:-1]) # 위와 같은 결과
print("="*80)


# 슬라이싱 이용한 배열 수정
slide_arr = b[1:3,1:5]
slide_arr[:,1:3]=9999
print(slide_arr)
print(b) # 원본까지 수정됨.(얕은 복사)

[  0   1   2   3   4 999   6   7   8   9  10  11  12  13  14  15  16  17
  18  19  20  21  22  23]
[  2   3   4 999]
[[   0    1    2    3    4    5]
 [   6    7 9999 9999   10   11]
 [  12   13 9999 9999   16   17]
 [  18   19   20   21   22   23]]
[[   2    3]
 [9999 9999]
 [9999 9999]
 [  20   21]]
[[   7 9999 9999   10]
 [  13 9999 9999   16]]
[[   7 9999 9999   10]
 [  13 9999 9999   16]]
[[   7 9999 9999   10]
 [  13 9999 9999   16]]
[[   0    1    2    3    4    5]
 [   6    7 9999 9999   10   11]
 [  12   13 9999 9999   16   17]
 [  18   19   20   21   22   23]]


불린 인덱싱(중요)

1. 배열 각 요소의 선택여부를 True, False로 표현한다.

2. 인덱스가 True인 아이템만 결과로 추출한다.

- 조건 걸리면 불린인덱싱

In [39]:
a = np.arange(24).reshape(4, 6)
pprint(a)

# ex) 짝수인 요소의 합계

#1. 배열 각 요소의 선택여부를 True, False로 표현합니다.

even_arr1 = a%2 # 브로드캐스팅(배열과 스칼라 연산)
print(even_arr1)
print("="*80)

even_arr2 = a%2 ==0 # True or False
print(even_arr2)
print("="*80)

# 2. 인덱스가 True인 아이템만 리턴.
print(a[a%2==0]) # [ 0  2  4  6  8 10 12 14 16 18 20 22]
print("="*80)


print(np.sum(a[a%2==0])) # 짝수
print(np.sum(a[a%2==1])) # 홀수

type: <class 'numpy.ndarray'>
shape: (4, 6), dimension: 2, dtype: int32
numpy 배열의 데이터
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
[[0 1 0 1 0 1]
 [0 1 0 1 0 1]
 [0 1 0 1 0 1]
 [0 1 0 1 0 1]]
[[ True False  True False  True False]
 [ True False  True False  True False]
 [ True False  True False  True False]
 [ True False  True False  True False]]
[ 0  2  4  6  8 10 12 14 16 18 20 22]
132
144


불린 인덱싱 응용  with pandas  

- 행 : 데이터 1건, 열 : 특성. 열 하나 : 시리즈


ex) 2014년 시애틀 1월 평균 강수량?  

1. 판다스로 데이터프레임을 읽는다 - pd.read_csv

2. 강수량 열(PRCP)의 데이터만 얻어온다 - rain_in_seattle.PRCP.values

3. 1년치 데이터 중 불린인덱스로 1월로 true인 데이터만 뽑아 평균을 구한다


데이터 파일 => ./data/Seattle2014.csv


In [42]:
import pandas as pd

In [ ]:
rain_in_seattle = pd.read_csv('./data/Seattle2014.csv') # csv파일을 데이터 프레임으로 읽어들인다
print(type(rain_in_seattle)) # DataFrame
rain_in_seattle

In [60]:
# 강수량 열(PRCP) 만 추출

# 1. 데이터프레임의 시리즈 추출  
# rain_arr = rain_in_seattle['PRCP']
# rain_arr = rain_in_seattle.get('PRCP')
rain_arr = rain_in_seattle.PRCP
print(rain_arr)
print(type(rain_arr)) # Series

0       0
1      41
2      15
3       0
4       0
       ..
360    33
361    41
362     0
363     0
364     0
Name: PRCP, Length: 365, dtype: int64
<class 'pandas.core.series.Series'>


In [62]:
rain_arr = rain_in_seattle.PRCP.values # 2. Series의 데이터만 'numpy.ndarray' 형태로 얻어온다.
print(type(rain_arr)) # <class 'numpy.ndarray'>
print(rain_arr)
print('Data Size:', len(rain_arr))

<class 'numpy.ndarray'>
[  0  41  15   0   0   3 122  97  58  43 213  15   0   0   0   0   0   0
   0   0   0   5   0   0   0   0   0  89 216   0  23  20   0   0   0   0
   0   0  51   5 183 170  46  18  94 117 264 145 152  10  30  28  25  61
 130   3   0   0   0   5 191 107 165 467  30   0 323  43 188   0   0   5
  69  81 277   3   0   5   0   0   0   0   0  41  36   3 221 140   0   0
   0   0  25   0  46   0   0  46   0   0   0   0   0   0   5 109 185   0
 137   0  51 142  89 124   0  33  69   0   0   0   0   0 333 160  51   0
   0 137  20   5   0   0   0   0   0   0   0   0   0   0   0   0  38   0
  56   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
  18  64   0   5  36  13   0   8   3   0   0   0   0   0   0  18  23   0
   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
   0   0   0   0   3 193   0   0   0   0   0   0   0   0   0   5   0   0
   0   0   0   0   0   0   5 127 216   0  10   0   0   0   0   0   0   0
   0   0   0   0   0   0   

In [72]:
days_arr = np.arange(365) # 1일~365일 배열
# print(days_arr)

# 1. 1월의 날수만큼 불린 인덱스를 생성한다
condition_jan = days_arr < 31 # 31일만큼 True
# print(condition_jan)

# 2. 불린 인덱스를 이용해 1월의 강수량을 추출
rain_jan = rain_arr[condition_jan]
print(rain_jan)

# 3. 평균 구한다
print('1월 강수량 평균 : {:4.1f}'.format(np.mean(rain_jan)))# 4자리에 소수첫째까지 나오는 실수

[  0  41  15   0   0   3 122  97  58  43 213  15   0   0   0   0   0   0
   0   0   0   5   0   0   0   0   0  89 216   0  23]
1월 강수량 평균 : 30.3


팬시 인덱싱 : 
배열에 인덱스 배열을 전달해 요소를 참조하는 방법

In [79]:
a = np.arange(1, 25).reshape(4, 6)
print(a)
print(a[0, 0], a[1, 1] ,a[2, 2], a[3, 3])
print('=' * 80)
print(a[[0, 1, 2, 3], (0, 1, 2, 3)]) # 팬시 인덱싱. 위와 같은 결과
print(a[[0, 1, 2, 3], (5, 4, 3, 2)]) # 6 11 16 21 

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]]
1 8 15 22
[ 1  8 15 22]
[ 6 11 16 21]


배열 변환(transform)

: 전치, 배열의 shape 변경, 배열 크기 변경, 배열 요소 추가, 배열 결합, 배열 분리.

1. 전치 : 행렬의 인덱스 바꿈.

2. shape 변경 :reshape(), ravel().
- reshape(): 데이터 변경없이 지정된 shape으로 변환.
- ravel() : 배열의 shape를 1차원으로 변경.(cnn : 이미지 인식, rnn : 글자 인식. 시계열 데이터)


3. resize() : 배열의 shape과 크기를 변경.
- 늘어난 요소에는 0 또는 기존 데이터가 채워진다.
- 줄어든 요소의 데이터는 분실된다.

4. append() : 배열 끝에 데이터 추가. axis로 방향 지정

- axis=None : 1차원 배열로 변환되어 결합. 기본값.

- axis=0 : 행방향 appending. 열의 개수는 반드시 같아야함. 다르면 오류

- axis=1 : 열방향 appending.  행의 개수는 반드시 같아야 한다. 

5. insert(), delete()  : 지정한 index에 데이터를 삽입. 삭제 axis로 방향 지정
- np.insert(배열 이름, index, [삽입할 데이터], axis)

6. 배열 결합 : np.concatenate(), np.vstack(), np.hstack().
- np.concatenate((배열1, 배열2, ...), axis)
- np.vstack((배열1, 배열2, ...)) : 수직 방향(axis=0)으로 결합한다.
- np.hstack((배열1, 배열2, ...)) : 수평 방향(axis=1)으로 결합한다.

7. 배열 분리
- 수직 방향으로 분할하는 np.vsplit(), 수평 방향으로 분할하는 np.hsplit().


In [105]:
a = np.arange(1,7).reshape(3,2)
print(a)
print(a.T) # 1. 전치 : .T

print('=' * 80)


a = np.random.randint(1, 10, (2, 3))
print(a)
print(a.ravel()) # 2. ravel : 1차원으로 반환



[[1 2]
 [3 4]
 [5 6]]
[[1 3 5]
 [2 4 6]]
[[8 1 1]
 [2 6 2]]
[8 1 1 2 6 2]


In [94]:
# cf) ravel() , reshape() 함수가 반환한 배열은 얕은 복사이다. 이를 수정하면 원본 내용도 수정된다. (이해완. 넘겨도됨)
b = a.ravel()
print(b)
b[4] = 999
print(b)
print('=' * 80)
print(a)


a = np.random.randint(1, 10, (2, 3))
print(a)
print('=' * 80)
b = a.reshape(3, 2, 1)
print(b)
print('=' * 80)
b[0][0][0] = 999
print(b)
print('=' * 80)
print(a)


[999   9   3   9   4   2]
[999   9   3   9 999   2]
[[999   9   3]
 [  9 999   2]]
[[7 6 4]
 [8 3 1]]
[[[7]
  [6]]

 [[4]
  [8]]

 [[3]
  [1]]]
[[[999]
  [  6]]

 [[  4]
  [  8]]

 [[  3]
  [  1]]]
[[999   6   4]
 [  8   3   1]]


In [107]:
a = np.random.randint(1, 10, (2, 6))
print(a)
print(np.resize(a, (6, 2))) # np.resize(a) :shape 변경 리턴한다. 
b = np.resize(a, (6, 2)) 
print(b)
a = np.random.randint(1, 10, (2, 6))
print(a)
a.resize(6, 2) # 배열.resize() : 원본 배열의 shape이 변경된다. ㅈㄴ 별거아닌데 길게설명함
print(a)
print('=' * 80)




[[6 7 9 2 8 2]
 [9 4 5 9 2 8]]
[[6 7]
 [9 2]
 [8 2]
 [9 4]
 [5 9]
 [2 8]]
[[6 7]
 [9 2]
 [8 2]
 [9 4]
 [5 9]
 [2 8]]
[[9 7 9 7 9 1]
 [2 7 7 5 9 9]]
[[9 7]
 [9 7]
 [9 1]
 [2 7]
 [7 5]
 [9 9]]


In [108]:
# 요소의 크기가 변경되는 resize() 함수
a = np.random.randint(1, 10, (2, 6)) 
print(a)
# a.reshape(2, 10) # reshape() : 원본과 요소의 개수가 다르면 에러.
a.resize(2, 10) # 배열의 요소 개수가 12개에서 20개로 늘어나고 늘어난 요소에는 0이 채워진다.
print(a)
a.resize(2, 4) # 배열의 요소 개수가 20개에서 8개로 줄어들고 줄어든 요소의 데이터는 분실된다.
print(a)
print('=' * 80)

a = np.random.randint(1, 10, (2, 6))
print(a)
a = np.resize(a, (2, 10)) # 늘어난 요소에 원본 배열 데이터가 반복돼 채워진다.
print(a)

[[9 2 6 9 4 8]
 [8 1 6 8 8 6]]
[[9 2 6 9 4 8 8 1 6 8]
 [8 6 0 0 0 0 0 0 0 0]]
[[9 2 6 9]
 [4 8 8 1]]
[[5 1 4 4 3 3]
 [2 7 1 8 9 6]]
[[5 1 4 4 3 3 2 7 1 8]
 [9 6 5 1 4 4 3 3 2 7]]


In [115]:
a = np.random.randint(1, 10, (3, 3))
print(a)
b = np.random.randint(10, 19, (3, 3))
print(b)

# axis=None : 1차원 배열로 변환되어 결합. 기본값.
result = np.append(a, b)
print(result)
result = np.append(a, b, axis=None) # 같음

# axis=0 : 행방향 appending. 열의 개수는 반드시 같아야함. 다르면 오류
result = np.append(a, b, axis=0) # a 배열 아래쪽에 b 배열이 추가.
print(result)
'''
[[ 6  1  7]
 [ 2  1  9]
 [ 2  1  1]
 [16 18 12]
 [15 15 17]
 [18 17 17]]
'''

diff_shape = np.random.randint(10, 19, (3, 2)) # a 배열과 열의 개수가 다른 배열
# result = np.append(a, diff_shape, axis=0) # 추가할 데이터가 a 배열과 열의 개수가 다르기 때문에 에러가 발생된다.
# print(result)



[[9 8 3]
 [5 9 4]
 [2 7 7]]
[[16 12 17]
 [18 14 15]
 [14 17 12]]
[ 9  8  3  5  9  4  2  7  7 16 12 17 18 14 15 14 17 12]
[[ 9  8  3]
 [ 5  9  4]
 [ 2  7  7]
 [16 12 17]
 [18 14 15]
 [14 17 12]]
[[18 12]
 [13 18]
 [15 17]]


In [118]:
# axis=1 : 열방향 appending.  행의 개수는 반드시 같아야 한다. 
result = np.append(a, b, axis=1) # a 배열 오른쪽에 b 배열이 추가된다.
print(result)
'''
[[ 6  1  7 16 18 12]
 [ 2  1  9 15 15 17]
 [ 2  1  1 18 17 17]]
'''
print('=' * 80)

diff_shape = np.random.randint(10, 19, (4, 3)) # a 배열과 행의 개수가 다른 배열
# print(diff_shape)
# result = np.append(a, diff_shape, axis=1) # 추가할 데이터가 a 배열과 행의 개수가 다르기 때문에 에러가 발생된다.
# print(result)


[[ 9  8  3 16 12 17]
 [ 5  9  4 18 14 15]
 [ 2  7  7 14 17 12]]


In [120]:
# np.insert(배열 이름, index, 삽입할 데이터, axis)

a = np.random.randint(1, 10, (3, 3))
print(a)
# axis= None : 기본값. 배열을 1차원으로 변환한 후 지정된 index에 데이터를 삽입한다.
print(np.insert(a, 1, 99999))
# print(np.insert(a, 1, 99999, axis=None))

# axis=0. 행방향 삽입
print(np.insert(a, 1, 99999, axis=0))
'''
[[    6     1     7]
 [99999 99999 99999]
 [    2     1     9]
 [    2     1     1]]
'''

# axis=1. 열방향 삽입
print(np.insert(a, 1, 99999, axis=1))
'''
[[    6 99999     1     7]
 [    2 99999     1     9]
 [    2 99999     1     1]]
 '''

[[6 7 8]
 [9 6 5]
 [4 9 4]]
[    6 99999     7     8     9     6     5     4     9     4]
[[    6     7     8]
 [99999 99999 99999]
 [    9     6     5]
 [    4     9     4]]
[[    6 99999     7     8]
 [    9 99999     6     5]
 [    4 99999     9     4]]


'\n[[    6 99999     1     7]\n [    2 99999     1     9]\n [    2 99999     1     1]]\n '

In [121]:
# delete

a = np.random.randint(1, 10, (3, 3))
print(a)
'''
[[1 5 7]
 [5 8 5]
 [6 4 9]]
'''
# axis를 지정하지 않으면 None이 기본값이고 배열을 1차원으로 변환한 후 지정된 index에 데이터를 삭제한다.
print(np.delete(a, 1))
print(np.delete(a, 1, axis=None))
'''
[1 7 5 8 5 6 4 9]
'''
# axis=0 행방향 삭제.
print(np.delete(a, 1, axis=0))
'''
[[1 5 7]
 [6 4 9]]
'''
# axis=1 열방향 삭제.
print(np.delete(a, 1, axis=1))
'''
[[1 7]
 [5 5]
 [6 9]]
'''


[[6 5 2]
 [6 7 4]
 [5 9 2]]
[6 2 6 7 4 5 9 2]
[6 2 6 7 4 5 9 2]
[[6 5 2]
 [5 9 2]]
[[6 2]
 [6 4]
 [5 2]]


'\n[[1 7]\n [5 5]\n [6 9]]\n'

In [123]:
# 배열 결합 - concatenate

a = np.random.randint(1, 10, (2, 3))
print(a)
b = np.random.randint(10, 19, (2, 3))
print(b)
'''
[[3 2 7]
 [8 9 3]]

[[18 18 16]
 [16 10 15]]
'''
# axis= 0이 기본값. 아래쪽으로 배열을 결합한다. 결합할 배열들이 열의 개수가 다르면 에러가 발생된다.
result = np.concatenate((a, b))
print(result)
result = np.concatenate((a, b), axis=0)
'''
[[ 3  2  7]
 [ 8  9  3]
 [18 18 16]
 [16 10 15]]
'''
# axis=1 열방향 오른쪽으로 배열을 결합한다. 행의 개수가 다르면 에러.
result = np.concatenate((a, b), axis=1)
print(result)


[[2 3 3]
 [6 4 2]]
[[18 12 16]
 [13 17 12]]
[[ 2  3  3]
 [ 6  4  2]
 [18 12 16]
 [13 17 12]]
[[ 2  3  3 18 12 16]
 [ 6  4  2 13 17 12]]


In [125]:
# np.vstack((배열1, 배열2, ...))
# np.hstack((a, b)

a = np.random.randint(1, 10, (2, 3))
print(a)
b = np.random.randint(10, 19, (2, 3))
print(b)
'''
[[3 7 1]
 [9 6 6]]
'''
'''
[[16 15 13]
 [13 10 18]]
'''
print(np.vstack((a, b))) # 열의 개수가 다르면 에러가 발생된다.
'''
[[ 3  7  1]
 [ 9  6  6]
 [16 15 13]
 [13 10 18]]

'''
print(np.hstack((a, b))) # 행의 개수가 다르면 에러가 발생된다.
'''
[[ 3  7  1 16 15 13]
 [ 9  6  6 13 10 18]]

'''



[[5 4 1]
 [8 3 5]]
[[17 11 18]
 [17 10 12]]
[[ 5  4  1]
 [ 8  3  5]
 [17 11 18]
 [17 10 12]]
[[ 5  4  1 17 11 18]
 [ 8  3  5 17 10 12]]


'\n[[ 3  7  1 16 15 13]\n [ 9  6  6 13 10 18]]\n\n'

In [131]:
# np.hsplit() 함수로 배열을 수평 방향으로 분할한다. axis = 1 y축기준.

a = np.arange(1, 25).reshape(4, 6)
'''
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]]
'''

result = np.hsplit(a, 3) # numpy 배열을 저장된 파이썬 list 형태로 리턴된다.
print(type(result)) # <class 'list'>
print(result)

# np.vsplit() 함수로 배열을 수직 방향으로 분할한다. axis = 0
# np.vsplit(배열 이름, 분할 배열의 개수)

result = np.vsplit(a, 4)
print(result)

<class 'list'>
[array([[ 1,  2],
       [ 7,  8],
       [13, 14],
       [19, 20]]), array([[ 3,  4],
       [ 9, 10],
       [15, 16],
       [21, 22]]), array([[ 5,  6],
       [11, 12],
       [17, 18],
       [23, 24]])]
[array([[1, 2, 3, 4, 5, 6]]), array([[ 7,  8,  9, 10, 11, 12]]), array([[13, 14, 15, 16, 17, 18]]), array([[19, 20, 21, 22, 23, 24]])]


[array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]]), array([[13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24]])]
