2차원 리스트

In [7]:
a = [[1, 2, 3], [4, 5, 6]]
print(a)

[[1, 2, 3], [4, 5, 6]]


외부 라이브러리를 커맨드(까만)창이 아니라 jupyter notebook에서 설치하기  
!pip install 라이브러리이름 => '!'를 붙여서 pip install을 실행하면 된다.

In [24]:
# !pip install numpy 
# numpy : 벡터 및 행렬 연산
import numpy as np

In [25]:
print(np.array(a))

[[1 2 3]
 [4 5 6]]


In [26]:
# 리스트이름 = [[0] * 열개수 for i in range(행개수)]
b = [[0] * 5 for i in range(4)]
print(b)

[[0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0]]


In [27]:

print(np.array(data))

[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]


In [28]:
print(len(b)) # 행의 개수
print(len(b[0])) # 열의 개수
# print(b.shape) # 에러
print(np.array(a).shape) # 2행3열
print(np.array(b).shape)
print(np.array(b).shape[0]) # 몇행이야?

4
5
(2, 3)
(4, 5)
4


In [29]:
for i in range(len(b)):
    print(b[i])

[0, 0, 0, 0, 0]
[0, 0, 0, 0, 0]
[0, 0, 0, 0, 0]
[0, 0, 0, 0, 0]


In [30]:
for i in range(len(b)): #행만큼반복. 4
    for j in range(len(b[i])): # 열. 5
        print(b[i][j], end=' ')
    print()

0 0 0 0 0 
0 0 0 0 0 
0 0 0 0 0 
0 0 0 0 0 


In [48]:
def pprint(data):
    for i in range(len(data)): # 행 출력. 4
        for j in range(len(data[i])): # 열 출력. 5 
            print('{:3d} '.format(data[i][j]), end=' ')
        print()

In [49]:
row, col = map(int, input('2차원 리스트를 만들려는 행과 열의 개수: ').split())
data = [[0] * col for i in range(row)]
n = 0 # 출력할 숫자.
print(data)
for i in range(len(data)): # 행
    # 짝수행은 숫자가 왼쪽에서 오른쪽으로 채워지고 홀수행은 숫자가 오른쪽에서 왼쪽으로 채워진다.
    if i % 2 == 0: # 짝수인가?
        # 짝수행은 왼쪽에서 오른쪽으로 숫자를 채운다. j => 0, 1, 2, 3, 4
        for j in range(col):
            n += 1
            data[i][j] = n
        # ===== for j
    else:
        # 홀수행은 오른쪽에서 왼쪽으로 숫자를 채운다. j => 4, 3, 2, 1, 0
        for j in range(col - 1, -1, -1):
            n += 1
            data[i][j] = n
        # ===== for j
    # ===== if
# ===== for i

pprint(data)

2차원 리스트를 만들려는 행과 열의 개수: 4 5
[[0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0]]
  1    2    3    4    5  
 10    9    8    7    6  
 11   12   13   14   15  
 20   19   18   17   16  


In [57]:
row, col = map(int, input('2차원 리스트를 만들려는 행과 열의 개수: ').split())
data = [[0] * col for i in range(row)]
n = 0
start = 0 # 2차원 리스트에 숫자가 채워지기 시작하는 열 인덱스
end = col - 1 # 마지막 열 인덱스
# 숫자가 채워지는 방향을 제어하는 변수 => start 부터 end 까지 증가치로 사용할 변수
sw = 1

for i in range(row):
    # i = 0, sw = 1, j = range(0, 5, 1) => 0, 1, 2, 3, 4
    # i = 1, sw = -1, j = range(4, -1, -1) => 4, 3, 2, 1, 0
    # i = 2, sw = 1, j = range(0, 5, 1) => 0, 1, 2, 3, 4
    # i = 3, sw = -1, j = range(4, -1, -1) => 4, 3, 2, 1, 0
    for j in range(start, end + sw, sw):
        n += 1
        data[i][j] = n
    # ===== for j
    start, end = end, start
    sw *= -1
# ===== for i

pprint(data)

2차원 리스트를 만들려는 행과 열의 개수: 3 5
  1    2    3    4    0  
  0    8    7    6    5  
  9   10   11   12    0  


In [55]:
row, col = map(int, input('2차원 리스트를 만들려는 행과 열의 개수: ').split())
data = [[0] * col for i in range(row)]
n = 0
start = [i for i in range(col)] # 왼쪽부터 오른쪽으로 진행하는 열 인덱스를 기억하는 리스트를 선언한다.
end = [i for i in range(col - 1, -1, -1)] # 오른쪽부터 왼쪽으로 진행하는 열 인덱스를 기억하는 리스트를 선언한다.
print(start,end)
for i in range(row):
    for j in start:
        n += 1
        data[i][j] = n
    # ===== for j
    start, end = end, start
# ===== for i

pprint(data)

2차원 리스트를 만들려는 행과 열의 개수: 3 5
[0, 1, 2, 3, 4] [4, 3, 2, 1, 0]
  1    2    3    4    5  
 10    9    8    7    6  
 11   12   13   14   15  
